### ISSUE TITLE
fails to build with ghc-8.0.2 and hackage-db-2.0

### ISSUE THREAD

**Issue by juhp** [jekor/hesh#9]
```
hesh/Main.hs:30:33: error:
    Module ‘Distribution.Hackage.DB’ does not export ‘readHackage’

hesh/Main.hs:30:46: error:
    Module ‘Distribution.Hackage.DB’ does not export ‘hackagePath’

hesh/Main.hs:33:30: error:
    Module ‘Distribution.Version’ does not export ‘versionBranch’
cabal: Leaving directory '/home/petersen/tmp/cabal-tmp-25299/hesh-1.11.0'
```

Seems to build okay with haskage-db-1.22 and `Data.Version`

**Comment by jekor** [comment]
Thanks for the report. I've added an upper bound in the .cabal file until I make it compile against >= 2.0.

119a68c30360c99f6a837f38259c34a63e49f8ee
